server:
  port: 8848

spring:
  datasource:
    url: jdbc:mysql://114.132.67.226:3306/chat_server?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: xiaoli
    password: abC123456@
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 114.132.67.226
    port: 6379
    password: abC123456@
